.\" Manual page for eXtremeSHOK.com ClamAV Unofficial Signature Updater
.TH clamav-unofficial-sigs 8 "16 October 2015" "Man Version 1.0" "SCRIPT COMMANDS"
.SH NAME
clamav-unofficial-sigs \- Download, test, and install third-party ClamAV signature databases.
.SH SYNOPSIS
.B clamav-unofficial-sigs
.RI [ options ]
.SH DESCRIPTION
\fBclamav-unofficial-sigs\fP script provides a simple way to download, test, and update third-party 
signature databases provided by Sanesecurity, FOXHOLE, OITC, Scamnailer, BOFHLAND, CRDF, Porcupine, 
Securiteinfo, MalwarePatrol. The package also contains cron, logrotate, and man files.
.SH UPDATES
Script updates can be found at: https://github.com/extremeshok/clamav-unofficial-sigs
.SH OPTIONS
This script follows the standard GNU command line syntax.
A summary of the options can be obtained by using the \-\-help command line switch
.SH SEE ALSO
.BR clamd (8),
.BR clamscan (1)
.SH COPYRIGHT
Copyright (c) Adrian Jon Kriel :: admin@extremeshok.com
.SH LICENSE
BSD (Berkeley Software Distribution)
.SH BUGS
Report bugs to https://github.com/extremeshok/clamav-unofficial-sigs
.SH AUTHOR
Adrian Jon Kriel :: admin@extremeshok.com
Originially based on Script provide by Bill Landry
